---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: ubuntu-22.04-android
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
  playbooks:
    prepare: ../default/prepare.yml
    converge: converge.yml
    verify: verify.yml
  inventory:
    host_vars:
      ubuntu-22.04-android:
        github_runner_personal_access_token: "test-token-android"
        github_runner_name: "test-runner-android"
        github_runner_repo: "test/repo"
        github_runner_labels: "self-hosted,android"
        github_runner_java: true
        github_runner_android: true
        github_runner_android_expose_adb_ports: true
        github_runner_adb_port: 5037
verifier:
  name: ansible
