---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: ubuntu-22.04-org
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ""
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
  playbooks:
    prepare: ../default/prepare.yml
    converge: converge.yml
    verify: verify.yml
  inventory:
    host_vars:
      ubuntu-22.04-org:
        github_runner_personal_access_token: "test-token-org"
        github_runner_name: "test-runner-org"
        github_runner_org: true
        github_runner_org_name: "test-org"
        github_runner_labels: "self-hosted,org"
verifier:
  name: ansible
