---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install Docker Python library
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Ensure Docker is accessible
      ansible.builtin.command: docker info
      register: docker_info
      changed_when: false
