---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install Docker CLI
      ansible.builtin.apt:
        name:
          - docker.io
        state: present

    - name: Install Docker Python library
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Ensure Docker is accessible
      ansible.builtin.command: docker info
      register: docker_info
      changed_when: false
