---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_version
      changed_when: false

    - name: Display Docker version
      ansible.builtin.debug:
        msg: "Docker version: {{ docker_version.stdout }}"

    - name: Check if GitHub runner container is running
      community.docker.docker_container_info:
        name: "{{ github_runner_name }}"
      register: runner_container

    - name: Verify container exists
      ansible.builtin.assert:
        that:
          - runner_container.exists
        fail_msg: "GitHub runner container does not exist"
        success_msg: "GitHub runner container exists"

    - name: Verify container is running
      ansible.builtin.assert:
        that:
          - runner_container.container.State.Running
        fail_msg: "GitHub runner container is not running"
        success_msg: "GitHub runner container is running"

    - name: Verify container is using non-Java image
      ansible.builtin.assert:
        that:
          - "'myoung34/github-runner' in runner_container.container.Config.Image"
        fail_msg: "GitHub runner container is not using the non-Java image"
        success_msg: "GitHub runner container is using the correct non-Java image"

    - name: Verify container restart policy
      ansible.builtin.assert:
        that:
          - runner_container.container.HostConfig.RestartPolicy.Name == "unless-stopped"
        fail_msg: "Container restart policy is not set correctly"
        success_msg: "Container restart policy is correct"

    - name: Debug container binds
      ansible.builtin.debug:
        var: runner_container.container.HostConfig.Binds

    - name: Verify docker socket is mounted
      ansible.builtin.assert:
        that:
          - runner_container.container.HostConfig.Binds is defined
          - runner_container.container.HostConfig.Binds | length > 0
          - runner_container.container.HostConfig.Binds | select('search', '/var/run/docker.sock') | list | length > 0
        fail_msg: "Docker socket is not mounted"
        success_msg: "Docker socket is mounted correctly"

    - name: Debug environment variables
      ansible.builtin.debug:
        var: runner_container.container.Config.Env

    - name: Verify RUNNER_SCOPE is NOT set for repo runners
      ansible.builtin.assert:
        that:
          - runner_container.container.Config.Env | select('match', '^RUNNER_SCOPE=') | list | length == 0
        fail_msg: "RUNNER_SCOPE should NOT be set for repository runners"
        success_msg: "RUNNER_SCOPE is correctly not set for repo runner"

    - name: Verify ORG_NAME is NOT set for repo runners
      ansible.builtin.assert:
        that:
          - runner_container.container.Config.Env | select('match', '^ORG_NAME=') | list | length == 0
        fail_msg: "ORG_NAME should NOT be set for repository runners"
        success_msg: "ORG_NAME is correctly not set for repo runner"

    - name: Verify REPO_URL is set for repo runners
      ansible.builtin.assert:
        that:
          - runner_container.container.Config.Env | select('match', '^REPO_URL=') | list | length > 0
        fail_msg: "REPO_URL should be set for repository runners"
        success_msg: "REPO_URL is correctly set for repo runner"
