---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Verify role variables are defined
      ansible.builtin.assert:
        that:
          - github_runner_name is defined
          - github_runner_repo is defined  
          - github_runner_personal_access_token is defined
          - github_runner_labels is defined
        fail_msg: "Required role variables are not properly defined"
        success_msg: "All required role variables are properly defined"

    - name: Test role execution completed
      ansible.builtin.debug:
        msg: "GitHub Runner role molecule testing completed successfully"