---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Test that role has the required variables defined
      ansible.builtin.assert:
        that:
          - github_runner_name is defined
          - github_runner_repo is defined
          - github_runner_personal_access_token is defined
        fail_msg: "Required variables are not defined"
        success_msg: "All required variables are properly defined"

    - name: Test role execution completed without errors
      ansible.builtin.debug:
        msg: "GitHub Runner role verification completed successfully"