---
- name: Github Runner
  hosts: localhost
  roles:
    - role: compscidr.github_runner.github_runner
      vars:
        github_runner_name: "hello-java-android"
        github_runner_personal_access_token: "insert token here"
        github_runner_repo: "user/repo"
        github_runner_java: true
        github_runner_install_docker: false
    - role: compscidr.github_runner.github_runner
      vars:
        github_runner_name: "hello-no-java"
        github_runner_personal_access_token: "insert token here"
        github_runner_repo: "user/repo"
        github_runner_java: false
        github_runner_install_docker: false
    - role: compscidr.github_runner.github_runner
      vars:
        github_runner_name: "hello-org-no-java"
        github_runner_personal_access_token: "insert token here"
        github_runner_org: true
        github_runner_org_name: "some org"
        github_runner_java: false
        github_runner_install_docker: false
