name: Test
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: ""
          setup_python: true
          working_directory: ""
          requirements_file: ""

  # TODO: Re-enable molecule tests when collections can be installed
  # Issue: galaxy.ansible.com is blocked in CI environment  
  # molecule:
  #   name: Molecule Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5
  #     
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.12'
  #     
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements-dev.txt
  #     
  #     - name: Create roles symlink for molecule
  #       run: |
  #         ln -sf ../../roles molecule/default/roles
  #     
  #     - name: Start Docker daemon
  #       run: |
  #         sudo systemctl start docker
  #         sudo chmod 666 /var/run/docker.sock
  #     
  #     - name: Run Molecule tests
  #       run: molecule test
  #       env:
  #         MOLECULE_NO_LOG: false
